name: conceptualize
description: PET project for clean architecture pattern
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dio: ^5.4.0
  json_annotation: ^4.8.1
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  get_it: ^7.6.6
  retrofit: ^4.1.0
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.8
  retrofit_generator: ^8.0.6
  json_serializable: 
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
